# Generated by Django 4.2.3 on 2023-09-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_classroom_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.CharField(default='', max_length=640, unique=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.CharField(default='', max_length=320, unique=True),
        ),
    ]
