# Generated by Django 4.2.3 on 2023-09-28 01:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_classroom_teacher_classroom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(default=api.models.generate_unique_code, max_length=16, unique=True),
        ),
    ]
