# Generated by Django 4.2.3 on 2023-09-28 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.CharField(default='', max_length=640),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teachers',
            field=models.CharField(default='', max_length=320),
        ),
    ]
