# Generated by Django 4.2.3 on 2023-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classrooms',
            field=models.CharField(default='', max_length=640),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
