# Generated by Django 4.2.3 on 2023-12-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_classrooms_alter_user_password_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_chapter',
            field=models.CharField(default='', max_length=32),
        ),
    ]
