# Generated by Django 4.2.3 on 2023-12-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_current_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classrooms',
            field=models.CharField(default='', max_length=640, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_chapter',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
